# numpy

### Numpy
#### Numerical Python
To install numpy use the following<br>
$sudo pip3.6 install numpy



In [1]:
import numpy

In [2]:
#array basics
import numpy as np
a = np.array([1,2,3]) #Create a rank one array
print(type(a)) #Prints "<class 'numpy.ndarray'>"
print(a.shape) #Prints "(3,)" #rows vs columns
print(a[0],a[1],a[2]) #prints 1 2 3
a[0] = 5 #change an element of an array
print(a) #prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [13]:
#1 row 3 colums
a = np.array([1,2,3])
print(a.shape)

#3 rows 1 colums
d = np.array([[1],[2],[3]])
print(d.shape)
print(a,"\n",d)

(3,)
(3, 1)
[1 2 3] 
 [[1]
 [2]
 [3]]


In [10]:
#another example
b = np.array([[1,2,3],[4,5,6]]) #Create rank 2 array
print(b.shape) # Prints (2, 3)
print(b[0,0],b[0,1],b[1,0]) #prints "1 2 4"

(2, 3)
1 2 4


In [16]:
#create numpy array from list
list1 = [[1,2,3],[3,4,5],[7,8,9]]
c = np.array(list1)
print(c)
print(c[0,1],c[1,1],c[2,2])

[[1 2 3]
 [3 4 5]
 [7 8 9]]
2 4 9


#### Numpy also provides functions to create arrays

In [23]:
import numpy as np

a = np.zeros((2,2)) #Create an array of all zeroes
print(a) #prints "[[0. 0.]"
           #      [0. 0.]]
print(type(a[0,0])) #prints "<class 'numpy.float64'>"


b = np.ones((1,2)) #Create an array of all ones
print(b) #Prints "[[1. 1.]]"
print(type(b[0,1])) #prints "<class 'numpy.float64'>"


c = np.full((2,2),7) #create a constant array 
print(c) #prints "[[7 7]
        #         [7 7]]"
print(type(c[1,1])) #Prints "<class 'numpy.int64'>"



[[0. 0.]
 [0. 0.]]
<class 'numpy.float64'>
[[1. 1.]]
<class 'numpy.float64'>
[[7 7]
 [7 7]]
<class 'numpy.int64'>


In [31]:
#Create a zeroes array of size - 4 by 3
#Create a ones array of size - 4 by 3
#Create a constant array of size - 4 by 3 - 8.5

d = np.zeros((4,3))
print(d,"\n")

e = np.ones((4,3))
print(e,"\n")

f = np.full((4,3),8.5)
print(f)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[8.5 8.5 8.5]
 [8.5 8.5 8.5]
 [8.5 8.5 8.5]
 [8.5 8.5 8.5]]
[[1. 0.]
 [0. 1.]]


In [34]:
#Ideniity Matrix
g = np.eye(3) #create a 2x2 identity matrix
print(g) #print "[[1. 0. 0.]
        #        [0. 1. 0.]
         #      [0. 0. 1.]]"

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Identity matrix

In [36]:
#Create Identity array of size 4x4
h = np.eye(4)
print(h)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Random Matrix

In [42]:
#create an array filled with random numbers
i = np.random.random((2,2))
print(i,"\n") #prints 2x2 random elements

#create arandom matrix of 3 by 4
j = np.random.random((3,4))
print(j)

[[0.0580711  0.98702674]
 [0.16612315 0.29033032]] 

[[0.74233676 0.54022311 0.62493353 0.96602787]
 [0.49546487 0.32031372 0.210662   0.25086585]
 [0.54083309 0.7940969  0.31425488 0.12751547]]


## Array Indexing
Numpy offers several ways to index into arrays

Slicing: Similar to python lists, numpy arrays can be sliced.<br>
Since arrays mat be multidimensional, you must specify a slice for each dimension of the array

In [54]:
import numpy as np
#create the following rank 2 array with shape (3,4)
#[[1 2 3 4]
#[5 6 7 8]
#[9 10 11 12]]

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a,"\n")

#Use slicing to pull out the subarray consisting of the first 2 rows
#and columns 1 and 2; b in the following array of shape(2,2)
# [[2 3]
# [6 7]]
b = a[:2,1:3]
print("shape =",b.shape)
print(b,"\n")

#A slice of an array is a view into the same data, so modifying the sliced array
#will modify the original array from which the sliced array was made
print("a[0,1]=",a[0,1],"\n")
b[0,0] = 77
print(b,"\n")
print("a[0,1]=",a[0,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

shape = (2, 2)
[[2 3]
 [6 7]] 

a[0,1]= 2 

[[77  3]
 [ 6  7]] 

a[0,1]= 77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
a = np.array([[3,7,2,10],[4,2,10,22],[3,6,15,21]])
print(a,"\n")
b = a[1:,1:3]
print("sliced array:\n",b)
print("\nb[1,1]=",b[1,1],"\na[2,2]=",a[2,2])
b[1,1] = 30
print("\nb[1,1]=",b[1,1],"\na[2,2]=",a[2,2])


[[ 3  7  2 10]
 [ 4  2 10 22]
 [ 3  6 15 21]] 

sliced array:
 [[ 2 10]
 [ 6 15]]

b[1,1]= 15 
a[2,2]= 15

b[1,1]= 30 
a[2,2]= 30


#### One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix

In [72]:
import numpy as np
#create  a new array
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a,"\n")

#create an array of indices
b = np.array([0,2,0,1]) #has to be numpy array
print("b =",b,"\n")

#select one element from each row of a using the indices in b
print(a[np.arange(4),b],"\n") #prints "[ 1  6  7 11]"

#Mutate one element from each row of a using the indices in b
a[np.arange(4),b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

b = [0 2 0 1] 

[ 1  6  7 11] 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### EX
Create a 3x3 array
23 34 56
2 -13 12
-14 20 16
Add 25 to the elements 23 -13 -14

In [80]:
a = np.array([[23, 34, 56],[-2, -13, 12],[-14, 20, 16]])
b = np.array([0,1,0])
a[np.arange(3),b]+=25
print(a)

[[48 34 56]
 [-2 12 12]
 [11 20 16]]


<b>Boolean array indexing:</b><br> Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfies some condition.

In [91]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])

bool_idx = (a>2) #Find the elements of 'a' that are bigger than 2
                 #this returns a numpy array of booleans 
                 #shape as a, where each slot of bool_idx
                 #whether that elememt is greater than 2
print(bool_idx,"\n") #print "[[False False]
                    #       [ True  True]
                   #       [ True  True]]"
#we use array indexing to construct a rank 1 array
#consisting of the element s of a corresponding to the True value of bool_idx
print("using bool_idx\n",a[bool_idx])
print(type(a[bool_idx]),"\n")

print(a[a>2],type(a[a>2])) #elements of 'a' of that are greater than 2
print(a[a<3],type(a[a>2])) #elements of 'a' of that are lesser than 3

[[False False]
 [ True  True]
 [ True  True]] 

using bool_idx
 [3 4 5 6]
<class 'numpy.ndarray'> 

[3 4 5 6] <class 'numpy.ndarray'>
[1 2] <class 'numpy.ndarray'>


## Array Math
Basic mathematical functions operate element wise on arays,and are available<br>
both as operator overloads and as functions in the numpy module

In [110]:
import numpy as np

x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

#Elementwise addition, both produce array
print("using basic operator '+'\n",x+y,"\n")
print("using np.add(x,y)\n",np.add(x,y),"\n",)
print("-------------------------------------")

#Elementwise difference, both produce array
print("using basic operator '-'\n",x-y,"\n")
print("using np.subtract(x,y)\n",np.subtract(x,y),"\n")
print("-------------------------------------")

#Elementwise division, both produce array
print("using basic operator '/'\n",x/y,"\n")
print("using np.divide(x,y)\n",np.divide(x,y),"\n")
print("-------------------------------------")

#Elementwise product, both produce array
print("using basic operator '*'\n",x*y,"\n")
print("using np.multiply(x,y)\n",np.multiply(x,y),"\n")
print("-------------------------------------")

#Elementwise squareroot, both produce array
print("using np.sqrt(x)\n",np.sqrt(x),"\n")
print("-------------------------------------")

using basic operator '+'
 [[ 6.  8.]
 [10. 12.]] 

using np.add(x,y)
 [[ 6.  8.]
 [10. 12.]] 

-------------------------------------
using basic operator '-'
 [[-4. -4.]
 [-4. -4.]] 

using np.subtract(x,y)
 [[-4. -4.]
 [-4. -4.]] 

-------------------------------------
using basic operator '/'
 [[0.2        0.33333333]
 [0.42857143 0.5       ]] 

using np.divide(x,y)
 [[0.2        0.33333333]
 [0.42857143 0.5       ]] 

-------------------------------------
using basic operator '*'
 [[ 5. 12.]
 [21. 32.]] 

using np.multiply(x,y)
 [[ 5. 12.]
 [21. 32.]] 

-------------------------------------
using np.sqrt(x)
 [[1.         1.41421356]
 [1.73205081 2.        ]] 

-------------------------------------


In [106]:
#single number multiplication
array3 = np.array([[1,2],[3,4]])
print("shape =",array3.shape,"\n")
print(array3*4,"\n")
print(array3/2.0,"\n")
print(array3+2,"\n")
print(array3-2)

shape = (2, 2) 

[[ 4  8]
 [12 16]] 

[[0.5 1. ]
 [1.5 2. ]] 

[[3 4]
 [5 6]] 

[[-1  0]
 [ 1  2]]


In [109]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(np.dot(x,y))
print(x.dot(y))



[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [111]:
import numpy as np
x = np.array([[1,2],[3,4]])

print(np.sum(x)) #computes sum of matrix and returns single number
print(np.sum(x,axis=0)) #Compute sum of each column; prints "[4 6]"
print(np.sum(x,axis=1)) #compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [117]:
import numpy as np
x = np.array([[1,2],[3,4]])
print("Original Matrix\n",x)
print("Transpose matrix\n",x.T,"\n")


#Transpose of rank 1 matrix does nothing
v = np.array([1,2,3])
print("Original Matrix\n",v)
print("Transpose matrix\n",v.T)

Original Matrix
 [[1 2]
 [3 4]]
Transpose matrix
 [[1 3]
 [2 4]] 

Original Matrix
 [1 2 3]
Transpose matrix
 [1 2 3]


<b>Q1. X = 3A - 4B</b><br>

<b>A:</b><br>
4 -2<br>
1 -7<br>

<b>B:</b><br>
-1 2<br>
6 5<br>
<b>------------------------------------------------------</b><br>
<b>Q2. X = A'A - 2A</b><br>

<b>A:</b><br>
3 -1<br>
0 2<br>

Solve for <b>X</b><br>
<b>------------------------------------------------------</b><br>
Solve for <b>X</b><br>
<b>Q3. X = 2AB + C</b><br>

<b>A:</b><br>
3 0 -1<br>
0 2 1<br>

<b>B:</b><br>
1 2<br>
1 0<br>
0 6<br>

<b>C:</b><br>
-2 0<br>
-2 -5<br>
<b>------------------------------------------------------</b><br>
Solve for <b>X</b><br>
<b>Q4. Proof the following using the given matrices:</b><br>

<b>A:</b><br>
10 12<br>
-7 -21<br>

<b>B:</b><br>
45 3<br>
12 -2<br>

<b>C:</b><br>
20 21<br>
-4 -5<br>

<b>i) (ABC)' = A'B'C'</b><br>
<b>ii) (A + B)' = A' + B'</b><br>
<b>iii) A(B + C) = AB + AC</b><br>

In [123]:
#1
import numpy as np
a = np.array([[4,-2],[1,-7]])
b = np.array([[-1, 2],[6,5]])
x = 3*a - 4*b
print(x)

[[ 16 -14]
 [-21 -41]]


In [127]:
#2
import numpy as np
a = np.array([[3,-1],[0,2]])
x = (a.T).dot(a) - 2*a
print(x)

[[ 3 -1]
 [-3  1]]


In [132]:
#3
import numpy as np
a = np.array([[3,0,-1],[0,2,1]])
b = np.array([[1,2],[1,0],[0,6]])
c = np.array([[-2,0],[-2,-5]])
x = 2*(a.dot(b)) + c
print(x)

[[4 0]
 [2 7]]


In [150]:
#4
import numpy as np
a = np.array([[10,12],[-7,-21]])
b = np.array([[45,3],[12,-2]])
c = np.array([[20,21],[-4,-5]])

#(i)
x = ((a.dot(b)).dot(c)).T
y = ((a.T).dot(b.T)).dot(c.T)
print("(ABC)' = A'B'C' is ",end="")
if False in (x==y):
    print("False")
else:
    print("True")

#(ii)
x = (a+b).T
y = a.T + b.T
print("(A + B)' = A' + B' is ",end="")
if False in (x==y):
    print("False")
else:
    print("True")

#(iii)
x = a.dot(b+c)
y = a.dot(b)+a.dot(c)
print("A(B + C) = AB + AC is ",end="")
if False in (x==y):
    print("False")
else:
    print("True")

(ABC)' = A'B'C' is False
(A + B)' = A' + B' is True
A(B + C) = AB + AC is True
True
